// import "./chapter1/binarySearch.js";
// import "./chapter1/evaluate.js";
// import "./chapter1/stack.js";
// import "./chapter1/queue.js";
// import "./chapter1/bag.js";
// import "./chapter1/reverse.js";
// import "./chapter1/josephus.js";
// import "./chapter1/threeSum.js";
// import "./chapter1/localMinimum.js";
import "./chapter1/throwEgg.js";
